.intel_syntax noprefix
	.section .rdata$slider_positive_table,"dr"
	.linkonce same_size
	.align 4096
.globl slider_positive_table
slider_positive_table:
# Generated by tools/generate_slider_positive_table.py.
# Metadata: mask * 4, eight bytes per reachable even mask, 256 KiB total.
# Shuffles: 262144 + mask * 8, sixteen bytes per even mask, 512 KiB total.
# Unused metadata rejects the mask; zero also has zero consumption metadata.
	.zero 40
	.long 0x000a, 0x04000001
	.zero 24
	.long 0x0012, 0x05000001
	.long 0x0014, 0x05000001
	.zero 48
	.long 0x0022, 0x06000001
	.long 0x0024, 0x06000001
	.zero 8
	.long 0x0028, 0x06000001
	.zero 104
	.long 0x0044, 0x07000001
	.zero 8
	.long 0x0048, 0x07000001
	.zero 248
	.long 0x0088, 0x08000001
	.zero 128
	.long 0x00aa, 0x08000002
	.zero 504
	.long 0x012a, 0x09000002
	.zero 120
	.long 0x014a, 0x09000002
	.zero 24
	.long 0x0152, 0x09000002
	.long 0x0154, 0x09000002
	.zero 848
	.long 0x022a, 0x0a000002
	.zero 120
	.long 0x024a, 0x0a000002
	.zero 24
	.long 0x0252, 0x0a000002
	.long 0x0254, 0x0a000002
	.zero 208
	.long 0x028a, 0x0a000002
	.zero 24
	.long 0x0292, 0x0a000002
	.long 0x0294, 0x0a000002
	.zero 48
	.long 0x02a2, 0x0a000002
	.long 0x02a4, 0x0a000002
	.zero 8
	.long 0x02a8, 0x0a000002
	.zero 1664
	.long 0x044a, 0x0b000002
	.zero 24
	.long 0x0452, 0x0b000002
	.long 0x0454, 0x0b000002
	.zero 208
	.long 0x048a, 0x0b000002
	.zero 24
	.long 0x0492, 0x0b000002
	.long 0x0494, 0x0b000002
	.zero 48
	.long 0x04a2, 0x0b000002
	.long 0x04a4, 0x0b000002
	.zero 8
	.long 0x04a8, 0x0b000002
	.zero 416
	.long 0x0512, 0x0b000002
	.long 0x0514, 0x0b000002
	.zero 48
	.long 0x0522, 0x0b000002
	.long 0x0524, 0x0b000002
	.zero 8
	.long 0x0528, 0x0b000002
	.zero 104
	.long 0x0544, 0x0b000002
	.zero 8
	.long 0x0548, 0x0b000002
	.zero 3328
	.long 0x088a, 0x0c000002
	.zero 24
	.long 0x0892, 0x0c000002
	.long 0x0894, 0x0c000002
	.zero 48
	.long 0x08a2, 0x0c000002
	.long 0x08a4, 0x0c000002
	.zero 8
	.long 0x08a8, 0x0c000002
	.zero 416
	.long 0x0912, 0x0c000002
	.long 0x0914, 0x0c000002
	.zero 48
	.long 0x0922, 0x0c000002
	.long 0x0924, 0x0c000002
	.zero 8
	.long 0x0928, 0x0c000002
	.zero 104
	.long 0x0944, 0x0c000002
	.zero 8
	.long 0x0948, 0x0c000002
	.zero 864
	.long 0x0a22, 0x0c000002
	.long 0x0a24, 0x0c000002
	.zero 8
	.long 0x0a28, 0x0c000002
	.zero 104
	.long 0x0a44, 0x0c000002
	.zero 8
	.long 0x0a48, 0x0c000002
	.zero 248
	.long 0x0a88, 0x0c000002
	.zero 6688
	.long 0x1112, 0x0d000002
	.long 0x1114, 0x0d000002
	.zero 48
	.long 0x1122, 0x0d000002
	.long 0x1124, 0x0d000002
	.zero 8
	.long 0x1128, 0x0d000002
	.zero 104
	.long 0x1144, 0x0d000002
	.zero 8
	.long 0x1148, 0x0d000002
	.zero 864
	.long 0x1222, 0x0d000002
	.long 0x1224, 0x0d000002
	.zero 8
	.long 0x1228, 0x0d000002
	.zero 104
	.long 0x1244, 0x0d000002
	.zero 8
	.long 0x1248, 0x0d000002
	.zero 248
	.long 0x1288, 0x0d000002
	.zero 1768
	.long 0x1444, 0x0d000002
	.zero 8
	.long 0x1448, 0x0d000002
	.zero 248
	.long 0x1488, 0x0d000002
	.zero 13920
	.long 0x2222, 0x0e000002
	.long 0x2224, 0x0e000002
	.zero 8
	.long 0x2228, 0x0e000002
	.zero 104
	.long 0x2244, 0x0e000002
	.zero 8
	.long 0x2248, 0x0e000002
	.zero 248
	.long 0x2288, 0x0e000002
	.zero 1768
	.long 0x2444, 0x0e000002
	.zero 8
	.long 0x2448, 0x0e000002
	.zero 248
	.long 0x2488, 0x0e000002
	.zero 4088
	.long 0x2888, 0x0e000002
	.zero 28392
	.long 0x4444, 0x0f000002
	.zero 8
	.long 0x4448, 0x0f000002
	.zero 248
	.long 0x4488, 0x0f000002
	.zero 4088
	.long 0x4888, 0x0f000002
	.zero 65528
	.long 0x8888, 0x10000002
	.zero 122328
	.zero 80
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 128, 128, 128, 128, 128, 128, 128
	.zero 48
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 128, 128, 128, 128, 128, 128, 128
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 128, 128, 128, 128, 128, 128, 128
	.zero 96
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 128, 128, 128, 128, 128, 128, 128
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 128, 128, 128, 128, 128, 128, 128
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 128, 128, 128, 128, 128, 128, 128
	.zero 208
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 128, 128, 128, 128, 128, 128, 128
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 128, 128, 128, 128, 128, 128, 128
	.zero 496
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 128, 128, 128, 128, 128, 128, 128
	.zero 256
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 128, 128, 4, 128, 128, 128, 6
	.zero 1008
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 128, 128, 4, 128, 128, 6, 7
	.zero 240
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 128, 4, 5, 128, 128, 128, 7
	.zero 48
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 128, 128, 5, 128, 128, 128, 7
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 128, 128, 5, 128, 128, 128, 7
	.zero 1696
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 128, 128, 4, 128, 6, 7, 8
	.zero 240
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 128, 4, 5, 128, 128, 7, 8
	.zero 48
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 128, 128, 5, 128, 128, 7, 8
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 128, 128, 5, 128, 128, 7, 8
	.zero 416
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 4, 5, 6, 128, 128, 128, 8
	.zero 48
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 128, 5, 6, 128, 128, 128, 8
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 128, 5, 6, 128, 128, 128, 8
	.zero 96
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 128, 128, 6, 128, 128, 128, 8
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 128, 128, 6, 128, 128, 128, 8
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 128, 128, 6, 128, 128, 128, 8
	.zero 3328
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 128, 4, 5, 128, 7, 8, 9
	.zero 48
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 128, 128, 5, 128, 7, 8, 9
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 128, 128, 5, 128, 7, 8, 9
	.zero 416
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 4, 5, 6, 128, 128, 8, 9
	.zero 48
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 128, 5, 6, 128, 128, 8, 9
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 128, 5, 6, 128, 128, 8, 9
	.zero 96
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 128, 128, 6, 128, 128, 8, 9
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 128, 128, 6, 128, 128, 8, 9
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 128, 128, 6, 128, 128, 8, 9
	.zero 832
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 5, 6, 7, 128, 128, 128, 9
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 5, 6, 7, 128, 128, 128, 9
	.zero 96
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 128, 6, 7, 128, 128, 128, 9
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 128, 6, 7, 128, 128, 128, 9
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 128, 6, 7, 128, 128, 128, 9
	.zero 208
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 128, 128, 7, 128, 128, 128, 9
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 128, 128, 7, 128, 128, 128, 9
	.zero 6656
	.byte 128, 128, 128, 0, 128, 128, 128, 2, 128, 4, 5, 6, 128, 8, 9, 10
	.zero 48
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 128, 5, 6, 128, 8, 9, 10
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 128, 5, 6, 128, 8, 9, 10
	.zero 96
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 128, 128, 6, 128, 8, 9, 10
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 128, 128, 6, 128, 8, 9, 10
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 128, 128, 6, 128, 8, 9, 10
	.zero 832
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 5, 6, 7, 128, 128, 9, 10
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 5, 6, 7, 128, 128, 9, 10
	.zero 96
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 128, 6, 7, 128, 128, 9, 10
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 128, 6, 7, 128, 128, 9, 10
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 128, 6, 7, 128, 128, 9, 10
	.zero 208
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 128, 128, 7, 128, 128, 9, 10
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 128, 128, 7, 128, 128, 9, 10
	.zero 1728
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 6, 7, 8, 128, 128, 128, 10
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 6, 7, 8, 128, 128, 128, 10
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 6, 7, 8, 128, 128, 128, 10
	.zero 208
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 128, 7, 8, 128, 128, 128, 10
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 128, 7, 8, 128, 128, 128, 10
	.zero 496
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 128, 128, 8, 128, 128, 128, 10
	.zero 13376
	.byte 128, 128, 128, 0, 128, 128, 2, 3, 128, 5, 6, 7, 128, 9, 10, 11
	.byte 128, 128, 0, 1, 128, 128, 128, 3, 128, 5, 6, 7, 128, 9, 10, 11
	.zero 96
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 128, 6, 7, 128, 9, 10, 11
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 128, 6, 7, 128, 9, 10, 11
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 128, 6, 7, 128, 9, 10, 11
	.zero 208
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 128, 128, 7, 128, 9, 10, 11
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 128, 128, 7, 128, 9, 10, 11
	.zero 1728
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 6, 7, 8, 128, 128, 10, 11
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 6, 7, 8, 128, 128, 10, 11
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 6, 7, 8, 128, 128, 10, 11
	.zero 208
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 128, 7, 8, 128, 128, 10, 11
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 128, 7, 8, 128, 128, 10, 11
	.zero 496
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 128, 128, 8, 128, 128, 10, 11
	.zero 3536
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 7, 8, 9, 128, 128, 128, 11
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 7, 8, 9, 128, 128, 128, 11
	.zero 496
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 128, 8, 9, 128, 128, 128, 11
	.zero 27840
	.byte 128, 128, 128, 0, 128, 2, 3, 4, 128, 6, 7, 8, 128, 10, 11, 12
	.byte 128, 128, 0, 1, 128, 128, 3, 4, 128, 6, 7, 8, 128, 10, 11, 12
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 128, 4, 128, 6, 7, 8, 128, 10, 11, 12
	.zero 208
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 128, 7, 8, 128, 10, 11, 12
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 128, 7, 8, 128, 10, 11, 12
	.zero 496
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 128, 128, 8, 128, 10, 11, 12
	.zero 3536
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 7, 8, 9, 128, 128, 11, 12
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 7, 8, 9, 128, 128, 11, 12
	.zero 496
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 128, 8, 9, 128, 128, 11, 12
	.zero 8176
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 8, 9, 10, 128, 128, 128, 12
	.zero 56784
	.byte 128, 128, 0, 1, 128, 3, 4, 5, 128, 7, 8, 9, 128, 11, 12, 13
	.zero 16
	.byte 128, 0, 1, 2, 128, 128, 4, 5, 128, 7, 8, 9, 128, 11, 12, 13
	.zero 496
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 128, 8, 9, 128, 11, 12, 13
	.zero 8176
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 8, 9, 10, 128, 128, 12, 13
	.zero 131056
	.byte 128, 0, 1, 2, 128, 4, 5, 6, 128, 8, 9, 10, 128, 12, 13, 14
	.zero 244656
	.section	.rdata$slider_single_table,"dr"
	.linkonce same_size
	.align 64
.globl slider_single_table
.globl slider_single_table
slider_single_table:
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	2
	.byte	-128
	.byte	4
	.byte	5
	.byte	6
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	2
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	-128
	.byte	-128
	.byte	2
	.byte	3
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	3
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	2
	.byte	-128
	.byte	-128
	.byte	4
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	-128
	.byte	3
	.byte	4
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	-128
	.byte	2
	.byte	3
	.byte	4
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	2
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	4
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	-128
	.byte	-128
	.byte	3
	.byte	4
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	136
	.space 12
	.long	10
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	18
	.space 12
	.long	-1
	.space 12
	.long	20
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	72
	.space 12
	.long	68
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	-1
	.space 12
	.long	34
	.space 12
	.long	40
	.space 12
	.long	36
	.space 12
	.section .rdata,"dr"
	.align 32
.globl slider_negative_table
.globl slider_negative_table
slider_negative_table:
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	-128
	.byte	3
	.byte	4
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	117440513
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	1
	.byte	-128
	.byte	3
	.byte	4
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	117440513
	.space 4
	.long	-1
	.long	1
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	-128
	.byte	1
	.byte	2
	.byte	-128
	.byte	-128
	.byte	4
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	117440513
	.space 4
	.long	-1
	.long	1
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	-128
	.byte	-128
	.byte	4
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	117440513
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	1
	.byte	-128
	.byte	-128
	.byte	4
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	117440513
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	1
	.byte	2
	.byte	3
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	117440513
	.space 4
	.long	-1
	.long	1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	3
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	83886081
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	3
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	83886081
	.space 4
	.long	-1
	.long	1
	.byte	-128
	.byte	0
	.byte	1
	.byte	2
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	117440513
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	1
	.byte	2
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	5
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	117440513
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	0
	.byte	-128
	.byte	-128
	.byte	3
	.byte	4
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	100663297
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	1
	.byte	-128
	.byte	-128
	.byte	3
	.byte	4
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	100663297
	.space 4
	.long	-1
	.long	1
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	-128
	.byte	1
	.byte	2
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	4
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	100663297
	.space 4
	.long	-1
	.long	1
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	4
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	100663297
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	4
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	100663297
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	1
	.byte	2
	.byte	3
	.byte	-128
	.byte	6
	.byte	7
	.byte	8
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	167772161
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	-128
	.byte	1
	.byte	2
	.byte	-128
	.byte	4
	.byte	5
	.byte	6
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	134217729
	.space 4
	.long	-1
	.long	1
	.byte	-128
	.byte	-128
	.byte	0
	.byte	1
	.byte	-128
	.byte	4
	.byte	5
	.byte	6
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	134217729
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	1
	.byte	-128
	.byte	4
	.byte	5
	.byte	6
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	134217729
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	1
	.byte	2
	.byte	3
	.byte	-128
	.byte	-128
	.byte	5
	.byte	6
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	134217729
	.space 4
	.long	-1
	.long	1
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	0
	.byte	1
	.byte	2
	.byte	-128
	.byte	-128
	.byte	5
	.byte	6
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	134217729
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	1
	.byte	2
	.byte	-128
	.byte	-128
	.byte	5
	.byte	6
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	134217729
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	1
	.byte	2
	.byte	3
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	6
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	134217729
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	1
	.byte	2
	.byte	3
	.byte	-128
	.byte	5
	.byte	6
	.byte	7
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	150994945
	.space 4
	.long	-1
	.long	1
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	0
	.byte	1
	.byte	2
	.byte	-128
	.byte	5
	.byte	6
	.byte	7
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	150994945
	.space 4
	.long	1
	.long	-1
	.byte	-128
	.byte	-128
	.byte	1
	.byte	2
	.byte	-128
	.byte	5
	.byte	6
	.byte	7
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	150994945
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.byte	-128
	.byte	1
	.byte	2
	.byte	3
	.byte	-128
	.byte	-128
	.byte	6
	.byte	7
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.byte	-128
	.long	150994945
	.space 4
	.long	-1
	.long	-1
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.space 16
	.long	268435457
	.space 12
	.long	-1
	.long	-1
	.long	70
	.long	69
	.long	-1
	.long	73
	.long	76
	.long	77
	.long	-1
	.long	81
	.long	22
	.long	21
	.long	88
	.long	89
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	38
	.long	37
	.long	-1
	.long	41
	.long	44
	.long	45
	.long	-1
	.long	561
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	137
	.long	140
	.long	141
	.long	-1
	.long	145
	.long	-1
	.long	-1
	.long	152
	.long	153
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	177
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	273
	.long	-1
	.long	-1
	.long	280
	.long	281
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	305
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.long	-1
	.globl	object_7_coordinate_shuffles
