"""Emit the direct positive-slider table; the remaining slider tables are separate."""
import itertools

entries = {}
for coordinates in (2, 4):
    for widths in itertools.product(range(1, 4), repeat=coordinates):
        cursor = mask = 0
        shuffle = [128] * 16
        for group, width in enumerate(widths):
            start = group * 4 + 4 - width
            shuffle[start:start + width] = range(cursor, cursor + width)
            cursor += width
            mask |= 1 << cursor
            cursor += 1
        metadata = coordinates // 2 | (cursor << 24)
        assert mask not in entries and not (mask & 1)
        entries[mask] = (metadata, shuffle)
assert len(entries) == 90

print('''\t.section .rdata$slider_positive_table,"dr"
\t.linkonce same_size
\t.align 4096
.globl slider_positive_table
slider_positive_table:
# Generated by tools/generate_slider_positive_table.py.
# Offset = delimiter mask * 16. Bit zero is excluded by the sign check,
# giving each reachable mask a full 32-byte entry within this 1 MiB table.
# Entry: mask, packed point-count/consumption, padding, 16-byte shuffle.
# Unused entries fail validation (mask zero also has zero return metadata).''')
cursor = 0
for mask, (metadata, shuffle) in sorted(entries.items()):
    offset = mask * 16
    assert offset >= cursor
    if offset != cursor:
        print(f'\t.zero {offset - cursor}')
    print(f'\t.long 0x{mask:04x}, 0x{metadata:08x}')
    print('\t.quad 0')
    print('\t.byte ' + ', '.join(map(str, shuffle)))
    cursor = offset + 32
print(f'\t.zero {0x100000 - cursor}')
